<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, HTML Slideshow Maker, Javascript for Slideshow" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="wow/engine1/style.css" />
	<script type="text/javascript" src="wow/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#f0f0f0">
<style type="text/css">
body{
overflow-x:hidden;}
</style>
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/dsc_0749.jpg" alt="DSC_0749" title="DSC_0749" id="wows1_0"/></li>
<li><img src="data1/images/dsc_0750.jpg" alt="DSC_0750" title="DSC_0750" id="wows1_1"/></li>
<li><img src="data1/images/dsc_0751.jpg" alt="DSC_0751" title="DSC_0751" id="wows1_2"/></li>
<li><img src="data1/images/dsc_0758.jpg" alt="DSC_0758" title="DSC_0758" id="wows1_3"/></li>
<li><img src="data1/images/dsc_0762.jpg" alt="DSC_0762" title="DSC_0762" id="wows1_4"/></li>
<li><img src="data1/images/dsc_0767.jpg" alt="DSC_0767" title="DSC_0767" id="wows1_5"/></li>
<li><img src="data1/images/dsc_0768.jpg" alt="DSC_0768" title="DSC_0768" id="wows1_6"/></li>
<li><img src="data1/images/dsc_0780.jpg" alt="DSC_0780" title="DSC_0780" id="wows1_7"/></li>
<li><img src="data1/images/dsc_0782.jpg" alt="DSC_0782" title="DSC_0782" id="wows1_8"/></li>
<li><img src="data1/images/dsc_0789.jpg" alt="DSC_0789" title="DSC_0789" id="wows1_9"/></li>
<li><img src="data1/images/dsc_0791.jpg" alt="DSC_0791" title="DSC_0791" id="wows1_10"/></li>
<li><img src="data1/images/dsc_0792.jpg" alt="DSC_0792" title="DSC_0792" id="wows1_11"/></li>
<li><img src="data1/images/dsc_0803.jpg" alt="DSC_0803" title="DSC_0803" id="wows1_12"/></li>
<li><img src="data1/images/dsc_0808.jpg" alt="DSC_0808" title="DSC_0808" id="wows1_13"/></li>
<li><img src="data1/images/dsc_0826.jpg" alt="DSC_0826" title="DSC_0826" id="wows1_14"/></li>
<li><img src="data1/images/dsc_0867.jpg" alt="DSC_0867" title="DSC_0867" id="wows1_15"/></li>
<li><img src="data1/images/dsc_0903.jpg" alt="DSC_0903" title="DSC_0903" id="wows1_16"/></li>
<li><img src="data1/images/dsc_0906.jpg" alt="DSC_0906" title="DSC_0906" id="wows1_17"/></li>
<li><img src="data1/images/dsc_0907.jpg" alt="DSC_0907" title="DSC_0907" id="wows1_18"/></li>
<li><img src="data1/images/dsc_0916.jpg" alt="DSC_0916" title="DSC_0916" id="wows1_19"/></li>
<li><img src="data1/images/dsc_0917.jpg" alt="DSC_0917" title="DSC_0917" id="wows1_20"/></li>
<li><img src="data1/images/dsc_0919.jpg" alt="DSC_0919" title="DSC_0919" id="wows1_21"/></li>
<li><img src="data1/images/dsc_0921.jpg" alt="DSC_0921" title="DSC_0921" id="wows1_22"/></li>
<li><img src="data1/images/dsc_0922.jpg" alt="DSC_0922" title="DSC_0922" id="wows1_23"/></li>
<li><img src="data1/images/dsc_0924.jpg" alt="DSC_0924" title="DSC_0924" id="wows1_24"/></li>
<li><img src="data1/images/dsc_0931.jpg" alt="DSC_0931" title="DSC_0931" id="wows1_25"/></li>
<li><img src="data1/images/dsc_0934.jpg" alt="DSC_0934" title="DSC_0934" id="wows1_26"/></li>
<li><img src="data1/images/dsc_0941.jpg" alt="DSC_0941" title="DSC_0941" id="wows1_27"/></li>
<li><img src="data1/images/dsc_0954.jpg" alt="DSC_0954" title="DSC_0954" id="wows1_28"/></li>
<li><img src="data1/images/dsc_0955.jpg" alt="DSC_0955" title="DSC_0955" id="wows1_29"/></li>
<li><img src="data1/images/dsc_0957.jpg" alt="DSC_0957" title="DSC_0957" id="wows1_30"/></li>
<li><img src="data1/images/dsc_0977.jpg" alt="DSC_0977" title="DSC_0977" id="wows1_31"/></li>
<li><img src="data1/images/dsc_0982.jpg" alt="DSC_0982" title="DSC_0982" id="wows1_32"/></li>
<li><img src="data1/images/dsc_0988.jpg" alt="DSC_0988" title="DSC_0988" id="wows1_33"/></li>
<li><img src="data1/images/dsc_0998.jpg" alt="DSC_0998" title="DSC_0998" id="wows1_34"/></li>
<li><img src="data1/images/dsc_0999.jpg" alt="DSC_0999" title="DSC_0999" id="wows1_35"/></li>
<li><img src="data1/images/dsc_1014.jpg" alt="DSC_1014" title="DSC_1014" id="wows1_36"/></li>
<li><img src="data1/images/dsc_1037.jpg" alt="DSC_1037" title="DSC_1037" id="wows1_37"/></li>
<li><img src="data1/images/dsc_1049.jpg" alt="DSC_1049" title="DSC_1049" id="wows1_38"/></li>
<li><img src="data1/images/dsc_1055.jpg" alt="DSC_1055" title="DSC_1055" id="wows1_39"/></li>
<li><img src="data1/images/dsc_1079.jpg" alt="DSC_1079" title="DSC_1079" id="wows1_40"/></li>
<li><img src="data1/images/dsc_1082.jpg" alt="DSC_1082" title="DSC_1082" id="wows1_41"/></li>
<li><img src="data1/images/dsc_1097.jpg" alt="DSC_1097" title="DSC_1097" id="wows1_42"/></li>
<li><img src="data1/images/dsc_1100.jpg" alt="DSC_1100" title="DSC_1100" id="wows1_43"/></li>
<li><img src="data1/images/dsc_1107.jpg" alt="DSC_1107" title="DSC_1107" id="wows1_44"/></li>
<li><img src="data1/images/dsc_1110.jpg" alt="DSC_1110" title="DSC_1110" id="wows1_45"/></li>
<li><img src="data1/images/dsc_1121.jpg" alt="DSC_1121" title="DSC_1121" id="wows1_46"/></li>
<li><img src="data1/images/dsc_1150.jpg" alt="DSC_1150" title="DSC_1150" id="wows1_47"/></li>
<li><img src="data1/images/dsc_1204.jpg" alt="DSC_1204" title="DSC_1204" id="wows1_48"/></li>
<li><img src="data1/images/dsc_1206.jpg" alt="DSC_1206" title="DSC_1206" id="wows1_49"/></li>
<li><img src="data1/images/dsc_1211.jpg" alt="DSC_1211" title="DSC_1211" id="wows1_50"/></li>
<li><img src="data1/images/dsc_1222.jpg" alt="DSC_1222" title="DSC_1222" id="wows1_51"/></li>
<li><img src="data1/images/dsc_1223.jpg" alt="DSC_1223" title="DSC_1223" id="wows1_52"/></li>
<li><img src="data1/images/dsc_1227.jpg" alt="DSC_1227" title="DSC_1227" id="wows1_53"/></li>
<li><img src="data1/images/dsc_1228.jpg" alt="DSC_1228" title="DSC_1228" id="wows1_54"/></li>
<li><img src="data1/images/dsc_1253.jpg" alt="DSC_1253" title="DSC_1253" id="wows1_55"/></li>
<li><img src="data1/images/dsc_1271.jpg" alt="DSC_1271" title="DSC_1271" id="wows1_56"/></li>
<li><img src="data1/images/dsc_1315.jpg" alt="DSC_1315" title="DSC_1315" id="wows1_57"/></li>
<li><img src="data1/images/dsc_0745.jpg" alt="DSC_0745" title="DSC_0745" id="wows1_58"/></li>
<li><img src="data1/images/dsc_0746.jpg" alt="DSC_0746" title="DSC_0746" id="wows1_59"/></li>
</ul></div>
<div class="ws_thumbs">
<div>
<a href="#" title="DSC_0749"><img src="data1/tooltips/dsc_0749.jpg" alt="" /></a>
<a href="#" title="DSC_0750"><img src="data1/tooltips/dsc_0750.jpg" alt="" /></a>
<a href="#" title="DSC_0751"><img src="data1/tooltips/dsc_0751.jpg" alt="" /></a>
<a href="#" title="DSC_0758"><img src="data1/tooltips/dsc_0758.jpg" alt="" /></a>
<a href="#" title="DSC_0762"><img src="data1/tooltips/dsc_0762.jpg" alt="" /></a>
<a href="#" title="DSC_0767"><img src="data1/tooltips/dsc_0767.jpg" alt="" /></a>
<a href="#" title="DSC_0768"><img src="data1/tooltips/dsc_0768.jpg" alt="" /></a>
<a href="#" title="DSC_0780"><img src="data1/tooltips/dsc_0780.jpg" alt="" /></a>
<a href="#" title="DSC_0782"><img src="data1/tooltips/dsc_0782.jpg" alt="" /></a>
<a href="#" title="DSC_0789"><img src="data1/tooltips/dsc_0789.jpg" alt="" /></a>
<a href="#" title="DSC_0791"><img src="data1/tooltips/dsc_0791.jpg" alt="" /></a>
<a href="#" title="DSC_0792"><img src="data1/tooltips/dsc_0792.jpg" alt="" /></a>
<a href="#" title="DSC_0803"><img src="data1/tooltips/dsc_0803.jpg" alt="" /></a>
<a href="#" title="DSC_0808"><img src="data1/tooltips/dsc_0808.jpg" alt="" /></a>
<a href="#" title="DSC_0826"><img src="data1/tooltips/dsc_0826.jpg" alt="" /></a>
<a href="#" title="DSC_0867"><img src="data1/tooltips/dsc_0867.jpg" alt="" /></a>
<a href="#" title="DSC_0903"><img src="data1/tooltips/dsc_0903.jpg" alt="" /></a>
<a href="#" title="DSC_0906"><img src="data1/tooltips/dsc_0906.jpg" alt="" /></a>
<a href="#" title="DSC_0907"><img src="data1/tooltips/dsc_0907.jpg" alt="" /></a>
<a href="#" title="DSC_0916"><img src="data1/tooltips/dsc_0916.jpg" alt="" /></a>
<a href="#" title="DSC_0917"><img src="data1/tooltips/dsc_0917.jpg" alt="" /></a>
<a href="#" title="DSC_0919"><img src="data1/tooltips/dsc_0919.jpg" alt="" /></a>
<a href="#" title="DSC_0921"><img src="data1/tooltips/dsc_0921.jpg" alt="" /></a>
<a href="#" title="DSC_0922"><img src="data1/tooltips/dsc_0922.jpg" alt="" /></a>
<a href="#" title="DSC_0924"><img src="data1/tooltips/dsc_0924.jpg" alt="" /></a>
<a href="#" title="DSC_0931"><img src="data1/tooltips/dsc_0931.jpg" alt="" /></a>
<a href="#" title="DSC_0934"><img src="data1/tooltips/dsc_0934.jpg" alt="" /></a>
<a href="#" title="DSC_0941"><img src="data1/tooltips/dsc_0941.jpg" alt="" /></a>
<a href="#" title="DSC_0954"><img src="data1/tooltips/dsc_0954.jpg" alt="" /></a>
<a href="#" title="DSC_0955"><img src="data1/tooltips/dsc_0955.jpg" alt="" /></a>
<a href="#" title="DSC_0957"><img src="data1/tooltips/dsc_0957.jpg" alt="" /></a>
<a href="#" title="DSC_0977"><img src="data1/tooltips/dsc_0977.jpg" alt="" /></a>
<a href="#" title="DSC_0982"><img src="data1/tooltips/dsc_0982.jpg" alt="" /></a>
<a href="#" title="DSC_0988"><img src="data1/tooltips/dsc_0988.jpg" alt="" /></a>
<a href="#" title="DSC_0998"><img src="data1/tooltips/dsc_0998.jpg" alt="" /></a>
<a href="#" title="DSC_0999"><img src="data1/tooltips/dsc_0999.jpg" alt="" /></a>
<a href="#" title="DSC_1014"><img src="data1/tooltips/dsc_1014.jpg" alt="" /></a>
<a href="#" title="DSC_1037"><img src="data1/tooltips/dsc_1037.jpg" alt="" /></a>
<a href="#" title="DSC_1049"><img src="data1/tooltips/dsc_1049.jpg" alt="" /></a>
<a href="#" title="DSC_1055"><img src="data1/tooltips/dsc_1055.jpg" alt="" /></a>
<a href="#" title="DSC_1079"><img src="data1/tooltips/dsc_1079.jpg" alt="" /></a>
<a href="#" title="DSC_1082"><img src="data1/tooltips/dsc_1082.jpg" alt="" /></a>
<a href="#" title="DSC_1097"><img src="data1/tooltips/dsc_1097.jpg" alt="" /></a>
<a href="#" title="DSC_1100"><img src="data1/tooltips/dsc_1100.jpg" alt="" /></a>
<a href="#" title="DSC_1107"><img src="data1/tooltips/dsc_1107.jpg" alt="" /></a>
<a href="#" title="DSC_1110"><img src="data1/tooltips/dsc_1110.jpg" alt="" /></a>
<a href="#" title="DSC_1121"><img src="data1/tooltips/dsc_1121.jpg" alt="" /></a>
<a href="#" title="DSC_1150"><img src="data1/tooltips/dsc_1150.jpg" alt="" /></a>
<a href="#" title="DSC_1204"><img src="data1/tooltips/dsc_1204.jpg" alt="" /></a>
<a href="#" title="DSC_1206"><img src="data1/tooltips/dsc_1206.jpg" alt="" /></a>
<a href="#" title="DSC_1211"><img src="data1/tooltips/dsc_1211.jpg" alt="" /></a>
<a href="#" title="DSC_1222"><img src="data1/tooltips/dsc_1222.jpg" alt="" /></a>
<a href="#" title="DSC_1223"><img src="data1/tooltips/dsc_1223.jpg" alt="" /></a>
<a href="#" title="DSC_1227"><img src="data1/tooltips/dsc_1227.jpg" alt="" /></a>
<a href="#" title="DSC_1228"><img src="data1/tooltips/dsc_1228.jpg" alt="" /></a>
<a href="#" title="DSC_1253"><img src="data1/tooltips/dsc_1253.jpg" alt="" /></a>
<a href="#" title="DSC_1271"><img src="data1/tooltips/dsc_1271.jpg" alt="" /></a>
<a href="#" title="DSC_1315"><img src="data1/tooltips/dsc_1315.jpg" alt="" /></a>
<a href="#" title="DSC_0745"><img src="data1/tooltips/dsc_0745.jpg" alt="" /></a>
<a href="#" title="DSC_0746"><img src="data1/tooltips/dsc_0746.jpg" alt="" /></a>
</div>
</div>
<span class="wsl"><a href="http://wowslider.com">Web Slide Show</a> by WOWSlider.com v4.2</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>